apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: tenant-2
  source:
    path: manifest/tennant-2/sample-app/overlays/dev
    repoURL: https://github.com/multi-tenant-example-org/tenant-2.git
    targetRevision: HEAD
