apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t2-sample-app
  namespace: argocd
spec:
  destination:
    namespace: tenant-2
    server: https://kubernetes.default.svc
  project: tenant-2
  source:
    path: manifests/tenant-2/sample-app/overlays/dev
    repoURL: https://github.com/multi-tenant-example-org/tenant-2.git
    targetRevision: HEAD
